<a href="https://colab.research.google.com/github/thiagotheiry05/Inteligencia_Artificial/blob/main/An%C3%A1lise%20de%20Dados/Anal%C3%ADse_de_dados_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### DESAFIO:

*   Obter o faturamento da loja
*   Obter produtos por loja vendidos
*   Obter o ticket Medio das vendas

In [3]:
# Importando o Pandas
import pandas as pd

In [5]:
# Lendo nossa tabela
tabela = pd.read_excel('VendasAnalise3.xlsx')
display(tabela)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
100995,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
100996,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
100998,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [6]:
# Fazendo com que a tabela fique sem nenhum dado indefinido
tabela = tabela.dropna(how='any', axis=0)
display(tabela)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
100995,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
100996,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
100998,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [7]:
# Verificando se alguma tabela está com o tipo errado
tabela.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100999 entries, 0 to 100998
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Código Venda    100999 non-null  int64
 1   Data            100999 non-null  datetime64[ns]
 2   ID Loja         100999 non-null  object
 3   Produto         100999 non-null  object
 4   Quantidade      100999 non-null  int64
 5   Valor Unitário  100999 non-null  int64
 6   Valor Final     100999 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 5.4+ MB

# Priemrio objetivo - Faturamento obitido

In [8]:
faturamento_loja = tabela[['ID Loja', 'Valor Final']].groupby('ID Loja').sum().reset_index()
display(faturamento_loja)
print()
faturamento_total = tabela['Valor Final'].sum()
print('O faturamento total foi de: ', faturamento_total)

                             ID Loja  Valor Final
0                Bourbon Shopping SP      1726110
1         Center Shopping Uberlândia      1668921
2                  Iguatemi Campinas      1762419
3                 Iguatemi Esplanada      1699681
4                     Norte Shopping      1711968
5       Novo Shopping Ribeirão Preto      1678225
6        Palladium Shopping Curitiba      1721120
7          Parque Dom Pedro Shopping      1631630
8          Passei das Águas Shopping      1649014
9                  Ribeirão Shopping      1707122
10                    Rio Mar Recife      1722766
11        Rio Mar Shopping Fortaleza      1698430
12                 Salvador Shopping      1646739
13                    Shopping Barra      1653103
14        Shopping Center Interlagos      1640486
15  Shopping Center Leste Aricanduva      1682870
16                 Shopping Eldorado      1648111
17               Shopping Ibirapuera      1635060
18       Shopping Iguatemi Fortaleza      1674824
19              Shopping Midway Mall      1590441
20                  Shopping Morumbi      1586444
21                   Shopping Recife      1624879
22                Shopping SP Market      1721763
23          Shopping União de Osasco      1663770
24               Shopping Vila Velha      1731167

O faturamento total foi de:  41877063

# Segundo Objetivo - Produtos vendidos por loja

In [12]:
# Produtos vendidos por loja
Produtos_loja = tabela[['ID Loja', 'Produto', 'Quantidade']].groupby(['ID Loja', 'Produto']).sum().reset_index()
display(Produtos_loja)

                  ID Loja           Produto  Quantidade
0     Bourbon Shopping SP           Bermuda          69
1     Bourbon Shopping SP   Bermuda Estampa          71
2     Bourbon Shopping SP     Bermuda Linho          61
3     Bourbon Shopping SP      Bermuda Liso          62
4     Bourbon Shopping SP  Bermuda Listrado          75
...                   ...               ...         ...
2995  Shopping Vila Velha     Tênis Estampa          66
2996  Shopping Vila Velha       Tênis Linho          86
2997  Shopping Vila Velha        Tênis Liso          65
2998  Shopping Vila Velha    Tênis Listrado          53
2999  Shopping Vila Velha      Tênis Xadrez          86

[3000 rows x 3 columns]

In [9]:
# Faturamento por loja
Produtos_fat = tabela[['ID Loja', 'Quantidade']].groupby('ID Loja').sum().reset_index()
display(Produtos_fat)

                             ID Loja  Quantidade
0                Bourbon Shopping SP        8863
1         Center Shopping Uberlândia        8627
2                  Iguatemi Campinas        8935
3                 Iguatemi Esplanada        8580
4                     Norte Shopping        9014
5       Novo Shopping Ribeirão Preto        8751
6        Palladium Shopping Curitiba        9091
7          Parque Dom Pedro Shopping        8388
8          Passei das Águas Shopping        8618
9                  Ribeirão Shopping        8825
10                    Rio Mar Recife        8863
11        Rio Mar Shopping Fortaleza        8937
12                 Salvador Shopping        8698
13                    Shopping Barra        8638
14        Shopping Center Interlagos        8675
15  Shopping Center Leste Aricanduva        8938
16                 Shopping Eldorado        8719
17               Shopping Ibirapuera        8723
18       Shopping Iguatemi Fortaleza        8629
19              Shopping Midway Mall        8206
20                  Shopping Morumbi        8508
21                   Shopping Recife        8581
22                Shopping SP Market        8927
23          Shopping União de Osasco        8730
24               Shopping Vila Velha        9224

# Terceiro Objetivo - Ticket medio de cada loja

In [ ]:
ticket_medio = faturamento_loja['Valor Final']/Produtos_Loja['Quantidade']
display(ticket_medio)

0     194.754598
1     193.453228
2     197.248909
3     198.098019
4     189.923231
5     191.775226
6     189.321307
7     194.519552
8     191.345324
9     193.441586
10    194.377299
11    190.044758
12    189.323868
13    191.375666
14    189.105014
15    188.282614
16    189.025232
17    187.442394
18    194.092479
19    193.814404
20    186.464974
21    189.357767
22    192.871401
23    190.580756
24    187.680724
dtype: float64

In [ ]:
tabela_ticket = pd.DataFrame({'Lojas': Produtos_Loja['ID Loja'], 'Ticket Medio' : ticket_medio})
display(tabela_ticket)

                               Lojas  Ticket Medio
0                Bourbon Shopping SP    194.754598
1         Center Shopping Uberlândia    193.453228
2                  Iguatemi Campinas    197.248909
3                 Iguatemi Esplanada    198.098019
4                     Norte Shopping    189.923231
5       Novo Shopping Ribeirão Preto    191.775226
6        Palladium Shopping Curitiba    189.321307
7          Parque Dom Pedro Shopping    194.519552
8          Passei das Águas Shopping    191.345324
9                  Ribeirão Shopping    193.441586
10                    Rio Mar Recife    194.377299
11        Rio Mar Shopping Fortaleza    190.044758
12                 Salvador Shopping    189.323868
13                    Shopping Barra    191.375666
14        Shopping Center Interlagos    189.105014
15  Shopping Center Leste Aricanduva    188.282614
16                 Shopping Eldorado    189.025232
17               Shopping Ibirapuera    187.442394
18       Shopping Iguatemi Fortaleza    194.092479
19              Shopping Midway Mall    193.814404
20                  Shopping Morumbi    186.464974
21                   Shopping Recife    189.357767
22                Shopping SP Market    192.871401
23          Shopping União de Osasco    190.580756
24               Shopping Vila Velha    187.680724